### ISSUE TITLE
Build error: readdir no such file

### ISSUE THREAD

**Issue by arvi** [Urigo/merge-graphql-schemas#148]
I can't seem to complete my build as it stops at merge-graphql-schemas package. I tried the ff but it didn't solve my issue: 
- yarn cache clean
- uninstall/install node modules
- update package from 1.4.0 to 1.5.2

Package version:
`merge-graphql-schemas": "1.5.2"`

Error:
```
return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/me/project/api/build/app/graphql/schema'
    at Object.fs.readdirSync (fs.js:904:18)
    at readDirSync (/Users/me/project/api/node_modules/merge-graphql-schemas/dist/index.cjs.js:3725:13)
    at getSchemaFiles (/Users/me/project/api/node_modules/merge-graphql-schemas/dist/index.cjs.js:3743:10)
    at fileLoader (/Users/me/project/api/node_modules/merge-graphql-schemas/dist/index.cjs.js:3758:21)
    at Object.<anonymous> (/Users/me/project/api/build/app/graphql/src/schema.js:5:108)
    at Module._compile (module.js:643:30)
```

Code:
```js
import { fileLoader, mergeResolvers, mergeTypes } from 'merge-graphql-schemas';
import path from 'path';

// merge all typedefs and resolvers to be used in graphql
export const typeDefs = mergeTypes(fileLoader(path.join(__dirname, '../../graphql/schema')));
export const resolvers = mergeResolvers(fileLoader(path.join(__dirname, '../../graphql/resolvers')));
```    

I think it is happening because `.graphql` files are not included during the `yarn run build`. Is it okay to move the schema folder at the same level as build and in my code access schema in that directory for both dev and build? Or the schema should be part of the build? Thanks for the advice.

**Comment by cfnelson** [comment]
@arvi What is `__dirname` outputting and where are the files located in the actual build bundle. Can you also let us know what your build tool/env is along with the version of node you are running? 
Is your bundler not including graphql files into your bundle?

**Comment by arojunior** [comment]
Hey, @arvi. I got the same problem, fixed just passing `--copy-files` argument in the build command.

ex:
```json
"scripts": {
   "build": "babel -d ./build ./src --copy-files"
}
```
I hope it help you.

**Comment by arvi** [comment]
@arojunior oooh! I'll try that.

I was able to solve mine via adding a script wherein it will copy graphql schema to the build folder wherein I called it `copy-static`

```json
    "clean": "rimraf build && mkdir build",
    "copy-static":
      "cp -R ./email/templates ./build/email && cp -R ./app/graphql/schema ./build/app/graphql/schema",
    "build":
      "yarn run clean && babel ./ --source-maps --out-dir build/ --ignore ./node_modules,./.babelrc,.editorconfig,.env,./package.json,./npm-debug.log,./cheatsheets",
    "preproduction":
      "yarn run build && yarn run copy-static && cross-env NODE_ENV=preproduction node bin/production",
    "production":
      "yarn run build && yarn run copy-static && cross-env NODE_ENV=production node bin/production",
```

@cfnelson, it's node v8.9.4, yarn 1.6.0 and with regards to my project directory:
```
|- api
|---- app
|-------- graphql
|------------- resolvers
|------------- schema (when I yarn run build... this folder is not included so I decided to create a script to copy it in the build file)
|- bin
|- build
|- uploads
|- email
|- node_modules
|- .babelrc
|- .env
|- .eslintrc.js
|- package.json
|- yarn.lock
```
