### ISSUE TITLE
Work with webpack permission error?

### ISSUE THREAD

**Issue by mrdulin** [Urigo/merge-graphql-schemas#164]
Here is error logs: 

```bash
☁  react-apollo-graphql-server [master] ⚡  npm start

> react-apollo-graphql-server@1.0.0 start /Users/ldu020/workspace/react-apollo-graphql-server
> node ./dist/index.js

/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2668
        throw er
        ^

Error: EACCES: permission denied, scandir '/Library/Application Support/Apple/AssetCache/Data'
    at Object.fs.readdirSync (fs.js:904:18)
    at GlobSync._readdir (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2615:41)
    at GlobSync._readdirInGlobStar (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2595:20)
    at GlobSync._readdir (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2603:17)
    at GlobSync._processReaddir (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2466:22)
    at GlobSync._process (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2461:10)
    at GlobSync._processGlobStar (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2707:10)
    at GlobSync._process (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2459:10)
    at GlobSync._processGlobStar (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2710:10)
    at GlobSync._process (/Users/ldu020/workspace/react-apollo-graphql-server/node_modules/merge-graphql-schemas/dist/index.cjs.js:2459:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-apollo-graphql-server@1.0.0 start: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-apollo-graphql-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ldu020/.npm/_logs/2018-09-14T08_30_29_718Z-debug.log
```

Here is my `webpack` config: 

```ts
import webpack from 'webpack';
import path from 'path';
import CleanWebpackPlugin from 'clean-webpack-plugin';
import nodeExternals from 'webpack-node-externals';

const src = path.resolve(__dirname, 'src');
const dist = path.resolve(__dirname, 'dist');

const config: webpack.Configuration = {
  target: 'node',
  entry: {
    app: src
  },
  output: {
    path: dist,
    filename: 'index.js',
    pathinfo: true
  },
  resolve: {
    extensions: ['.ts', '.js']
  },
  devtool: 'source-map',
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: 'ts-loader',
        exclude: /node_modules/
      }
    ]
  },
  plugins: [new CleanWebpackPlugin(dist)],
  externals: [nodeExternals()]
};

export default config;

```

`package.json`: 

```json
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack --mode=development",
    "start": "node ./dist/index.js"
  },
```

Need a example about `typescript` + `webpack`

**Comment by jwdinker** [comment]
Did you solve this?  I'm having the same problem with {recursive:true}

**Comment by RichardLitt** [comment]
@jwdinker Not that I know of. @cfnelson got any thoughts on this?

**Comment by cfnelson** [comment]
@jwdinker How are you using `fileLoader` ? Can you provide a code snippet 😃 
 What is your stack trace reporting? Specifically what dir is `fileLoader` trying to read when it throws `EACCES: permission denied, scandir` ?

That error implies that it's attempting to read a dir it doesn't have permission to access, e.g outside of your user space if your not running the app with root privileges.

If you can provide any more context/details similar to what mrdulin has provided along with logging the `process.cwd()` and `__dirname` before you pass it to `fileLoader` that would go a long way in understanding your issue. 🙌

**Comment by jwdinker** [comment]
@cfnelson finally figured it out.  This occurs if you are running globally. I was using the serverless-offline package and that was the problem.  I hard coded the directory and that resolved the issue.  Any tips on easier way to do this?

**Comment by ardatan** [comment]
Looks related to FS. Feel free to open a new issue if problem persists.

**Comment by or2008** [comment]
for anyone else having this issue, that was because __dirname was different on production build via webpack, check this for more info:
https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92
