### ISSUE TITLE
Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by rogerioasj** [Urigo/merge-graphql-schemas#189]
So, I'm merging multiple types and resolvers files this way:

`import * as path from "path";
import { fileLoader, mergeTypes, mergeResolvers } from "merge-graphql-schemas";

const typesArray = fileLoader(path.join(__dirname, "/**/*.types.js"));
const resolversArray = fileLoader(path.join(__dirname, "/**/*.resolvers.js"));

export const typeDefs = mergeTypes(typesArray);
export const resolvers = mergeResolvers(resolversArray);`

At runtime I get the following error:

> TypeError: Invalid attempt to spread non-iterable instance

At index.cjs.js, line 4532, my error is solved if `return ast.definitions;` is changed to `return ast.typeDefs.definitions;`.

**Comment by idkjs** [comment]
@rogerioasj I tried that, did not work, got this error:

```
TypeError: Cannot read property 'definitions' of undefined
```
Did you change anything else?

full error is below.
```
[nodemon] starting `babel-node ./app/server.js`
/Users/prisc_000/working/TUTORIALS/graphql-nodejs-modular-kit/node_modules/merge-graphql-schemas/dist/index.cjs.js:4532
    return ast.typeDefs.definitions;
                        ^

TypeError: Cannot read property 'definitions' of undefined
    at /Users/prisc_000/working/TUTORIALS/graphql-nodejs-modular-kit/node_modules/merge-graphql-schemas/dist/index.cjs.js:4532:25
    at Array.map (<anonymous>)
    at mergeTypes (/Users/prisc_000/working/TUTORIALS/graphql-nodejs-modular-kit/node_modules/merge-graphql-schemas/dist/index.cjs.js:4531:6)
    at Object.mergeTypes (/Users/prisc_000/working/TUTORIALS/graphql-nodejs-modular-kit/app/gRoute.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/prisc_000/.npm-global/lib/node_modules/@babel/node/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Users/prisc_000/.npm-global/lib/node_modules/@babel/node/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

thanks.

**Comment by rogerioasj** [comment]
Hi @idkjs, no, that was all I did.

**Comment by idkjs** [comment]
Thanks @rogerioasj

**Comment by SebastianEdwards** [comment]
Also hitting this error out of the blue

**Comment by SebastianEdwards** [comment]
Managed to fix this by rolling back webpack's raw-loader to an earlier version

**Comment by ardatan** [comment]
I think it is related to how you export type definitions from js modules. So feel free to open a new issue if the problem persists.
