### ISSUE TITLE
TypeError: is_glob_1.default is not a function

### ISSUE THREAD

**Issue by Fi1osof** [Urigo/merge-graphql-schemas#205]
v1.6.0 error. v 1.5.8 is OK
```
TypeError: is_glob_1.default is not a function
    at getSchemaFiles (/www/node_modules/merge-graphql-schemas/src/file_loader.ts:28:13)
    at fileLoader (/www/node_modules/merge-graphql-schemas/src/file_loader.ts:47:23)
    at Module.getSchema (file:///www/node_modules/@prisma-cms/marketplace-module/src/modules/index.mjs:44:18)
    at getModules.map.n (file:///www/node_modules/@prisma-cms/prisma-module/src/index.mjs:159:29)
    at Array.map (<anonymous>)
    at CoreModule.getSchema (file:///www/node_modules/@prisma-cms/prisma-module/src/index.mjs:157:23)
    at CoreModule.getSchema (file:///www/src/server/modules/index.mjs:89:28)
    at generateSchema (/www/node_modules/@prisma-cms/prisma-schema/lib/index.js:32:27)
    at generateSchema (file:///www/src/server/scripts/deploy/schema.mjs:21:14)
    at Promise (file:///www/node_modules/@prisma-cms/server/src/server/scripts/deploy/handlers.mjs:136:16)
    at new Promise (<anonymous>)
    at deploySchema (file:///www/node_modules/@prisma-cms/server/src/server/scripts/deploy/handlers.mjs:130:10)
    at deploy (file:///www/node_modules/@prisma-cms/server/src/server/scripts/deploy/index.mjs:26:16)
    at file:///www/src/server/scripts/deploy/with-prisma.mjs:10:3
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)

```

**Comment by dongnguyenvie** [comment]
thank u. i have same issues today.

**Comment by ardatan** [comment]
@Fi1osof @dongnguyenvie
Thank you for opening this issue.
Fixed in 1.6.1!

**Comment by kachkaev** [comment]
Many thanks @ardatan! The fix worked for me 🚀

**Comment by Fi1osof** [comment]
@ardatan thanks!
