### ISSUE TITLE
Error: Unknown type "Query".

### ISSUE THREAD

**Issue by josuevalrob** [Urigo/merge-graphql-schemas#354]
This piece of code: 
```
const path = require('path');
const mergeGraphqlSchemas = require('merge-graphql-schemas')
const fileLoader = mergeGraphqlSchemas.fileLoader
const mergeTypes = mergeGraphqlSchemas.mergeTypes

const typesArray = fileLoader(path.join(__dirname, '.'), { recursive: true })
const typeDefs = mergeTypes(typesArray, { all: true })
console.log(typeDefs)
export {typeDefs}
```

Return this: 
schema {
  query: Query
}

Any idea why??

I got this error: 

> 
> /Users/josuevalencia/WebDevelopment/osja/campLestel/api/node_modules/graphql/validation/validate.js:108
>     throw new Error(errors.map(function (error) {
>     ^
> 
> Error: Unknown type "Query".
>     at assertValidSDL (/Users/josuevalencia/WebDevelopment/osja/campLestel/api/node_modules/graphql/validation/validate.js:108:11)
>     at Object.buildASTSchema (/Users/josuevalencia/WebDevelopment/osja/campLestel/api/node_modules/graphql/utilities/buildASTSchema.js:71:34)
>     at Object.buildSchemaFromTypeDefinitions (/Users/josuevalencia/WebDevelopment/osja/campLestel/api/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)

**Comment by josuevalrob** [comment]
I found the problem. I am using ES6 and compiling with Babel to ES5: 

This is my typedef file: 

```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _mergeGraphqlSchemas = require("merge-graphql-schemas");

var typeDefs = "type Cliente {\n        id: ID\n        nombre: String\n        apellido: String\n        empresa: String\n        edad: Int\n        tipo: TipoCliente\n        pedidos:[Pedido]\n        # emails: [Email]\n        email: String\n    }\ntype Pedido {\n    producto: String\n    precio : Int\n}\ntype Email {\n    email : String\n}\n\"\"\" Assign the category client \"\"\"\nenum  TipoCliente {\n    BASICO\n    PREMIUM\n}\ninput PedidoInput {\n    producto: String\n    precio : Int\n}\ninput EmailInput {\n    email: String\n}\n\"\"\" fields for new clients \"\"\"\ninput ClienteInput {\n    id: ID\n    nombre: String!\n    apellido: String\n    empresa: String\n    edad: Int\n    pedidos:[PedidoInput]\n    tipo: TipoCliente\n    # emails: [EmailInput]!\n    email: String!\n\n} \n\"\"\"Query \"\"\"\ntype Query {\n    getCliente(id:ID) : Cliente\n    getClientes(limit: Int, offset:Int) : [Cliente]\n}\n\"\"\" Mutation to create new clients. \"\"\"\ntype Mutation {\n    #Nombre del resolver y el valor que retorna\n    \"\"\" xyxz...  \"\"\"\n    crearCliente(input:ClienteInput): Cliente\n    actualizarCliente(input: ClienteInput) : Cliente\n    eliminarCliente( id: ID! ) : String\n}";

var path = require('path');

var typesArray = (0, _mergeGraphqlSchemas.fileLoader)(path.join(__dirname, '.'), {
  recursive: true
});
var merge = (0, _mergeGraphqlSchemas.mergeTypes)(typesArray, {
  all: true
});
console.log(path.join(__dirname, '.')); // export {typeDefs}

var _default = typeDefs;
exports["default"] = _default;
```

Is becaouse I am using this babel configuration: 

```
{
    "presets": ["@babel/preset-env"],
    "plugins": [
      "import-graphql",
      [
        "@babel/plugin-transform-runtime",
        {"regenerator": true}
      ]
    ]
  }
  
```

How can I solve the proble??

**Comment by josuevalrob** [comment]
But for some reason this config works fine: 

```
import client from './client.graphql'
import user from './user.graphql'
import {mergeTypes} from 'merge-graphql-schemas'
const types = [
	client,
	user
];
export const typeDefs = mergeTypes(types, { all: true })
```
